insert into politicians(last_name) values ('BUHAY');
insert into politicians(last_name) values ('A TEACHER');
insert into politicians(last_name) values ('BAYAN MUNA');
insert into politicians(last_name) values ('1-CARE');
insert into politicians(last_name) values ('AKBAYAN');
insert into politicians(last_name) values ('AKB');
insert into politicians(last_name) values ('GABRIELA');
insert into politicians(last_name) values ('OFW FAMILY');
insert into politicians(last_name) values ('ABONO');
insert into politicians(last_name) values ('SENIOR CITIZENS');
insert into politicians(last_name) values ('COOP-NATCCO');
insert into politicians(last_name) values ('AGAP');
insert into politicians(last_name) values ('CIBAC');
insert into politicians(last_name) values ('MAGDALO');
insert into politicians(last_name) values ('AN WARAY');
insert into politicians(last_name) values ('BUTIL');
insert into politicians(last_name) values ('ACT TEACHERS');
insert into politicians(last_name) values ('ABAMIN');
insert into politicians(last_name) values ('TUCP');
insert into politicians(last_name) values ('KALINGA');
insert into politicians(last_name) values ('YACAP');
insert into politicians(last_name) values ('ACT-CIS');
insert into politicians(last_name) values ('ANGKLA');
insert into politicians(last_name) values ('ABS');
insert into politicians(last_name) values ('LPGMA');
insert into politicians(last_name) values ('AGRI');
insert into politicians(last_name) values ('KABATAAN');
insert into politicians(last_name) values ('DIWA');
insert into politicians(last_name) values ('ALAY BUHAY');
insert into politicians(last_name) values ('ANAKPAWIS');
insert into politicians(last_name) values ('1-SAGIP');
insert into politicians(last_name) values ('AAMBIS-OWA');
insert into politicians(last_name) values ('AVE');
insert into politicians(last_name) values ('ABANG LINGKOD');
insert into politicians(last_name) values ('AMIN');
insert into politicians(last_name) values ('ATING KOOP');
insert into politicians(last_name) values ('ABAKADA');
insert into politicians(last_name) values ('ANG NARS');
insert into politicians(last_name) values ('1-BAP');
insert into politicians(last_name) values ('APPEND');
insert into politicians(last_name) values ('AMA');
insert into politicians(last_name) values ('AGBIAG!');
insert into politicians(last_name) values ('ATING GURO');
insert into politicians(last_name) values ('ANAD');
insert into politicians(last_name) values ('PBA');
insert into politicians(last_name) values ('BH');
insert into politicians(last_name) values ('ANAC-IP');
insert into politicians(last_name) values ('ANG KASANGGA');
insert into politicians(last_name) values ('AANGAT TAYO');
insert into politicians(last_name) values ('BINHI');
insert into politicians(last_name) values ('PISTON');
insert into politicians(last_name) values ('ADA');
insert into politicians(last_name) values ('1-AALALAY');
insert into politicians(last_name) values ('ABANTE RETIREES');
insert into politicians(last_name) values ('BAYANI');
insert into politicians(last_name) values ('VFP');
insert into politicians(last_name) values ('ABROAD');
insert into politicians(last_name) values ('ALE');
insert into politicians(last_name) values ('1JAMG');
insert into politicians(last_name) values ('KAKUSA');
insert into politicians(last_name) values ('APEC');
insert into politicians(last_name) values ('ALIF');
insert into politicians(last_name) values ('PASANG MASDA');
insert into politicians(last_name) values ('ANG PROLIFE');
insert into politicians(last_name) values ('AGHAM');
insert into politicians(last_name) values ('1 ANG PAMILYA');
insert into politicians(last_name) values ('KATRIBU');
insert into politicians(last_name) values ('PACYAW');
insert into politicians(last_name) values ('AKMA-PTM');
insert into politicians(last_name) values ('1-UTAK');
insert into politicians(last_name) values ('AKAP BATA INC.');
insert into politicians(last_name) values ('1-PABAHAY');
insert into politicians(last_name) values ('1-LAMBAT');
insert into politicians(last_name) values ('BANTAY');
insert into politicians(last_name) values ('ABANTE KA');
insert into politicians(last_name) values ('ANG LADLAD');
insert into politicians(last_name) values ('FIRM 24-K');
insert into politicians(last_name) values ('COCOFED');
insert into politicians(last_name) values ('ABA');
insert into politicians(last_name) values ('1ST KABAGIS');
insert into politicians(last_name) values ('AANI');
insert into politicians(last_name) values ('PWD');
insert into politicians(last_name) values ('SANLAKAS');
insert into politicians(last_name) values ('ATONG PAGLAUM');
insert into politicians(last_name) values ('1 BRO-PGBI');
insert into politicians(last_name) values ('AKO');
insert into politicians(last_name) values ('ARAL');
insert into politicians(last_name) values ('ATM');
insert into politicians(last_name) values ('KAAKBAY');
insert into politicians(last_name) values ('AASENSO');
insert into politicians(last_name) values ('ANG MINERO');
insert into politicians(last_name) values ('AMA');
insert into politicians(last_name) values ('KAP');
insert into politicians(last_name) values ('1GANAP/GUARDIANS');
insert into politicians(last_name) values ('SMART');
insert into politicians(last_name) values ('ALIM');
insert into politicians(last_name) values ('ADAM');
insert into politicians(last_name) values ('AKO BAHAY');
insert into politicians(last_name) values ('1-AAMOVER');
insert into politicians(last_name) values ('ABP');
insert into politicians(last_name) values ('AA-KASOSYO');
insert into politicians(last_name) values ('ALYANSA NG OFW');
insert into politicians(last_name) values ('UMALAB KA');
insert into politicians(last_name) values ('ARC');
insert into politicians(last_name) values ('ADING');
insert into politicians(last_name) values ('AMOR SEAMAN');
insert into politicians(last_name) values ('A BLESSED');
insert into politicians(last_name) values ('AAMA');
insert into politicians(last_name) values ('UNI-MAD');
insert into politicians(last_name) values ('ARARO');
insert into politicians(last_name) values ('MIGRANTE');
insert into politicians(last_name) values ('MTM PHILS');
insert into politicians(last_name) values ('AWAT MINDANAO');
insert into politicians(last_name) values ('GREEN FORCE');
insert into politicians(last_name) values ('AGILA');
insert into politicians(last_name) values ('AMS');
insert into politicians(last_name) values ('ALAGAD');
insert into politicians(last_name) values ('A-IPRA');
insert into politicians(last_name) values ('AFPSEGCO');
insert into politicians(last_name) values ('KLBP');
insert into politicians(last_name) values ('1-ABILIDAD');
insert into politicians(last_name) values ('ALLUMAD');
insert into politicians(last_name) values ('AG');

insert into careers(start_date, title, politician_id, location_id)
  select to_date('05/13/2013', 'MM/DD/YYYY'), 'party-list', id,
    (select id from locations where name = 'nationwide')
  from politicians
  where id >= (
    select id
    from politicians
    where last_name = 'BUHAY' and first_name is null
  );
